openapi: 3.0.1
info:
  title: Devlog
  description: Devlog API
  version: 0.1.0
servers:
- url: https://localhost:8080
tags: []
paths:
  /demo:
    get:
      tags:
      - demo
      operationId: demo
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/demo-1637600963"
              examples:
                demo:
                  value: "{\"result\":\"SUCCESS\",\"data\":\"demo\",\"error\":null}"
components:
  schemas:
    demo-1637600963:
      type: object
      properties:
        result:
          type: string
          description: "The result of the operation (e.g., SUCCESS)"
        data:
          type: string
          description: "The data returned by the API (e.g., demo)"
