# 게시글 생성
POST localhost:8080/api/admin/articles
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBhZG1pbi5jb20iLCJyb2xlcyI6WyJST0xFX0FETUlOIiwiUk9MRV9VU0VSIl0sImlhdCI6MTczNTg3MzYzNSwiZXhwIjoxNzM1ODc3MjM1fQ.VReETNaikfH6JU4Mg0bXOVGljGr3IaJQkR-oITXf35QKqIOX68M6b9SYGdvZ0Av6wWcFWGgPk_aaUNaG3Oj3lA
Content-Type: application/json

{
  "title": "AWS",
  "author": "jungmini",
  "description": "AWS 관련 게시글",
  "link": "https://example.com",
  "category": "AWS",
  "tags": [
    "태그1",
    "태그2",
    "태그3"
  ]
}

###

# 게시글 수정
PUT localhost:8080/api/admin/articles/6
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBnb29nbGUuY29tIiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJpYXQiOjE3MzU0NzAwOTIsImV4cCI6MTczNTQ3MzY5Mn0.LILhXcOiZ0W2nunpNM90JzhQiUayP8Yt_2Q36hL_sW4q8bts2OWBMqtp_njt8EPOz-awXrBk16mes0X0RzNnxQ
Content-Type: application/json

{
  "title": "예제 수정",
  "author": "작성자 수정",
  "description": "이것은 예제 설명입니다.",
  "link": "https://example.com",
  "category": "기술",
  "tags": [
    "태그10",
    "태그20",
    "태그30"
  ]
}

###

# 게시글 삭제
DELETE localhost:8080/api/admin/articles/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBhZG1pbi5jb20iLCJyb2xlcyI6WyJST0xFX0FETUlOIiwiUk9MRV9VU0VSIl0sImlhdCI6MTczNTcwNTE0MywiZXhwIjoxNzM1NzA4NzQzfQ.sHHN_-zl_pVjzKbDDT2fuTxU69NS5G3JrEr3naITEfUugW4EfrUATumfzjdeNq4vpfjWfzC_mF6hLw-3BIsJWg
Content-Type: application/json

###

# 게시글 좋아요
POST localhost:8080/api/articles/2/like
Content-Type: application/json

###

# 게시글 좋아요 취소
DELETE localhost:8080/api/articles/1/like
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBhZG1pbi5jb20iLCJyb2xlcyI6WyJST0xFX0FETUlOIiwiUk9MRV9VU0VSIl0sImlhdCI6MTczNTg2NjA1NCwiZXhwIjoxNzM1ODY5NjU0fQ.ADVMaVj55hgIuIht2vmymBVTc1PtAn6sAfM_2eFQq_FLZ5v2nDnroW6sR3YaAlwisldjfz1oxn387wZvLT6dxA
Content-Type: application/json

###

# 게시글 북마크
POST localhost:8080/api/articles/1/bookMark
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBhZG1pbi5jb20iLCJyb2xlcyI6WyJST0xFX0FETUlOIiwiUk9MRV9VU0VSIl0sImlhdCI6MTczNTg3MTMxNiwiZXhwIjoxNzM1ODc0OTE2fQ.y-uVpcjXQM55RNt3jKE5n5J0jZtAMSS0jZ9mzF4qm6leI5xGh_ZzeY4B1XUpwezxGyYdLRmNW4JY5JqP0CdMWg
Content-Type: application/json

###

# 게시글 북마크 취소
DELETE localhost:8080/api/articles/1/bookMark
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBhZG1pbi5jb20iLCJyb2xlcyI6WyJST0xFX0FETUlOIiwiUk9MRV9VU0VSIl0sImlhdCI6MTczNTg3MTMxNiwiZXhwIjoxNzM1ODc0OTE2fQ.y-uVpcjXQM55RNt3jKE5n5J0jZtAMSS0jZ9mzF4qm6leI5xGh_ZzeY4B1XUpwezxGyYdLRmNW4JY5JqP0CdMWg
Content-Type: application/json