# 게시글 생성
POST localhost:8080/api/admin/articles
Content-Type: application/json

{
  "title": "예제 제목",
  "author": "작성자 이름",
  "description": "이것은 예제 설명입니다.",
  "link": "https://example.com",
  "category": "기술",
  "tags": [
    "태그11",
    "태그2",
    "태그3"
  ]
}