# 로그인
POST localhost:8080/api/auth/token
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "admin1234"
}

###

# 토큰재발급
POST localhost:8080/api/auth/token/refresh
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0QHRlc3QuY29tIiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJpYXQiOjE3MzUyMDczODMsImV4cCI6MTczNTIxMDk4M30.io2aqtp6JdA3jRIK8mdlG9l7es8Ls5S8KPrz9kMYYYdw2s6pWdnXbG0dL-L3nQ-BgXvY5kNGcsj76gJ4PMwuGQ"
}